import React, { useState, useEffect } from "react";
import {
  Wind,
  Activity,
  TrendingUp,
  MapPin,
  Clock,
  AlertCircle,
  Info,
  Droplets,
  Thermometer,
  Eye,
  Heart,
  Loader,
  Download,
  Share2,
  Calendar,
  Sun,
  Cloud,
  Zap,
  Users,
  Building2,
} from "lucide-react";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Area,
  AreaChart,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  PieChart,
  Pie,
  Cell,
} from "recharts";

const AirAwareDashboard = () => {
  const [currentData, setCurrentData] = useState(null);
  const [historicalData, setHistoricalData] = useState([]);
  const [weeklyData, setWeeklyData] = useState([]);
  const [pollutantData, setPollutantData] = useState([]);
  const [radarData, setRadarData] = useState([]);
  const [sourceData, setSourceData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("overview");
  const [timeRange, setTimeRange] = useState("24h");

  const handleShare = async () => {
    const shareData = {
      title: 'AirAware - Air Quality Dashboard',
      text: `Current AQI: ${currentData?.aqi || 'N/A'} - ${currentData ? getAQICategory(currentData.aqi).label : 'Loading'}`,
      url: window.location.href
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
      } else {
        await navigator.clipboard.writeText(`${shareData.title}\n${shareData.text}\n${shareData.url}`);
        alert('Dashboard info copied to clipboard!');
      }
    } catch (err) {
      console.error('Error sharing:', err);
    }
  };

  const handleDownload = () => {
    if (!currentData) return;

    const category = getAQICategory(currentData.aqi);
    const reportContent = `
AIR QUALITY REPORT
==================
Generated: ${new Date().toLocaleString()}
Location: Delhi, India

CURRENT CONDITIONS
------------------
AQI: ${currentData.aqi} (${category.label})
Status: ${category.desc}
Dominant Pollutant: ${currentData.dominantPollutant}

POLLUTANT LEVELS
----------------
PM2.5: ${currentData.pm25} µg/m³
PM10: ${currentData.pm10} µg/m³
NO₂: ${currentData.no2} µg/m³
SO₂: ${currentData.so2} µg/m³
CO: ${currentData.co} mg/m³
O₃: ${currentData.o3} µg/m³

WEATHER CONDITIONS
------------------
Temperature: ${currentData.temperature}°C
Humidity: ${currentData.humidity}%
Wind Speed: ${currentData.windSpeed} km/h ${currentData.windDirection}
Visibility: ${currentData.visibility} km
UV Index: ${currentData.uvIndex}
Pressure: ${currentData.pressure} hPa

HEALTH RECOMMENDATION
---------------------
${category.recommendation}

---
Report generated by AirAware
Data sources: EPA, WHO, Local Monitoring Stations
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `air-quality-report-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  useEffect(() => {
    const fetchData = () => {
      const current = {
        aqi: 156,
        category: "Unhealthy",
        color: "#f97316",
        pm25: 85.4,
        pm10: 142.8,
        no2: 45.2,
        so2: 12.5,
        co: 1.8,
        o3: 68.3,
        temperature: 28.5,
        humidity: 62,
        windSpeed: 12.4,
        windDirection: "NW",
        pressure: 1012.5,
        visibility: 4.2,
        uvIndex: 7,
        timestamp: new Date().toLocaleTimeString(),
        date: new Date().toLocaleDateString(),
        dominantPollutant: "PM2.5",
      };

      const historical = Array.from({ length: 24 }, (_, i) => {
        const baseAQI = 120;
        const variation = Math.sin(i / 3) * 30;
        return {
          hour: `${i.toString().padStart(2, "0")}:00`,
          aqi: Math.floor(baseAQI + variation + Math.random() * 20),
          pm25: Math.floor(60 + variation * 0.5 + Math.random() * 20),
          pm10: Math.floor(100 + variation * 0.8 + Math.random() * 30),
          no2: Math.floor(40 + Math.random() * 15),
          temp: Math.floor(24 + i * 0.3 + Math.random() * 2),
        };
      });

      const weekly = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(
        (day) => ({
          day,
          avgAQI: Math.floor(120 + Math.random() * 60),
          maxAQI: Math.floor(160 + Math.random() * 40),
          minAQI: Math.floor(80 + Math.random() * 30),
        })
      );

      const pollutants = [
        {
          name: "PM2.5",
          value: 85.4,
          limit: 35.4,
          unit: "µg/m³",
          impact: "High",
          trend: "increasing",
          healthEffect: "Respiratory issues, heart problems",
        },
        {
          name: "PM10",
          value: 142.8,
          limit: 154,
          unit: "µg/m³",
          impact: "Moderate",
          trend: "stable",
          healthEffect: "Breathing difficulties",
        },
        {
          name: "NO₂",
          value: 45.2,
          limit: 100,
          unit: "µg/m³",
          impact: "Low",
          trend: "decreasing",
          healthEffect: "Lung inflammation",
        },
        {
          name: "SO₂",
          value: 12.5,
          limit: 75,
          unit: "µg/m³",
          impact: "Low",
          trend: "stable",
          healthEffect: "Asthma triggers",
        },
        {
          name: "CO",
          value: 1.8,
          limit: 9,
          unit: "mg/m³",
          impact: "Low",
          trend: "stable",
          healthEffect: "Reduced oxygen delivery",
        },
        {
          name: "O₃",
          value: 68.3,
          limit: 100,
          unit: "µg/m³",
          impact: "Moderate",
          trend: "increasing",
          healthEffect: "Chest pain, coughing",
        },
      ];

      const radar = [
        { pollutant: "PM2.5", current: 85, safe: 35 },
        { pollutant: "PM10", current: 143, safe: 154 },
        { pollutant: "NO₂", current: 45, safe: 100 },
        { pollutant: "SO₂", current: 13, safe: 75 },
        { pollutant: "CO", current: 1.8, safe: 9 },
        { pollutant: "O₃", current: 68, safe: 100 },
      ];

      const sources = [
        { name: "Vehicles", value: 35, color: "#ef4444" },
        { name: "Industries", value: 28, color: "#f97316" },
        { name: "Construction", value: 15, color: "#fbbf24" },
        { name: "Biomass Burning", value: 12, color: "#84cc16" },
        { name: "Others", value: 10, color: "#3b82f6" },
      ];

      setCurrentData(current);
      setHistoricalData(historical);
      setWeeklyData(weekly);
      setPollutantData(pollutants);
      setRadarData(radar);
      setSourceData(sources);
      setLoading(false);
    };

    fetchData();
    const interval = setInterval(fetchData, 60000);
    return () => clearInterval(interval);
  }, []);

  const getAQICategory = (aqi) => {
    if (aqi <= 50)
      return {
        label: "Good",
        desc: "Air quality is satisfactory, and air pollution poses little or no risk",
        recommendation: "Perfect day for outdoor activities",
      };
    if (aqi <= 100)
      return {
        label: "Moderate",
        desc: "Air quality is acceptable. However, there may be a risk for some people",
        recommendation:
          "Sensitive individuals should limit prolonged outdoor exertion",
      };
    if (aqi <= 150)
      return {
        label: "Unhealthy for Sensitive Groups",
        desc: "Members of sensitive groups may experience health effects",
        recommendation:
          "Children, elderly, and people with respiratory issues should reduce outdoor activities",
      };
    if (aqi <= 200)
      return {
        label: "Unhealthy",
        desc: "Some members of the general public may experience health effects",
        recommendation:
          "Everyone should reduce prolonged or heavy outdoor exertion",
      };
    if (aqi <= 300)
      return {
        label: "Very Unhealthy",
        desc: "Health alert: The risk of health effects is increased for everyone",
        recommendation:
          "Avoid all outdoor activities. Use air purifiers indoors",
      };
    return {
      label: "Hazardous",
      desc: "Health warning of emergency conditions: everyone is more likely to be affected",
      recommendation:
        "Stay indoors. Keep windows closed. Use N95 masks if going outside",
    };
  };

  const getTrendIcon = (trend) => {
    if (trend === "increasing") return "📈";
    if (trend === "decreasing") return "📉";
    return "➡️";
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-center">
          <Loader className="w-16 h-16 text-purple-400 animate-spin mx-auto mb-4" />
          <div className="text-white text-2xl font-semibold">
            Loading AirAware...
          </div>
          <p className="text-gray-400 mt-2">Fetching latest air quality data</p>
        </div>
      </div>
    );
  }

  const category = getAQICategory(currentData.aqi);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <header className="bg-white/10 backdrop-blur-md border-b border-white/20 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-gradient-to-br from-blue-400 to-purple-500 p-2 rounded-xl">
                <Wind className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white flex items-center">
                  AirAware
                  <span className="ml-2 px-2 py-0.5 text-xs bg-green-500/20 text-green-300 rounded-full border border-green-500/30">
                    Live
                  </span>
                </h1>
                <p className="text-sm text-gray-300">
                  Real-time Air Quality Intelligence
                </p>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <div className="hidden md:flex items-center space-x-2 text-white bg-white/10 px-4 py-2 rounded-lg">
                <MapPin className="w-5 h-5" />
                <span className="font-medium">Delhi, India</span>
              </div>
              <button 
                onClick={handleShare}
                className="p-2 hover:bg-white/10 rounded-lg transition-colors"
                title="Share Dashboard"
              >
                <Share2 className="w-5 h-5 text-white" />
              </button>
              <button 
                onClick={handleDownload}
                className="p-2 hover:bg-white/10 rounded-lg transition-colors"
                title="Download Report"
              >
                <Download className="w-5 h-5 text-white" />
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
        <div
          className="mb-6 rounded-2xl p-6 flex items-start space-x-4 shadow-2xl"
          style={{
            backgroundColor: `${currentData.color}15`,
            borderLeft: `6px solid ${currentData.color}`,
            border: `1px solid ${currentData.color}40`,
          }}
        >
          <AlertCircle
            className="w-8 h-8 flex-shrink-0 mt-1"
            style={{ color: currentData.color }}
          />
          <div className="flex-1">
            <div className="flex items-center justify-between mb-2">
              <p className="font-bold text-xl text-white">
                {category.label} Air Quality
              </p>
              <span className="text-sm text-gray-300">
                {currentData.date} | {currentData.timestamp}
              </span>
            </div>
            <p className="text-gray-300 mb-3">{category.desc}</p>
            <div className="bg-white/5 rounded-lg p-3 border border-white/10">
              <p className="text-sm font-semibold text-white mb-1">
                💡 Health Recommendation:
              </p>
              <p className="text-sm text-gray-300">{category.recommendation}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[
            {
              label: "Dominant Pollutant",
              value: currentData.dominantPollutant,
              icon: Activity,
              color: "from-red-500 to-orange-500",
            },
            {
              label: "Visibility",
              value: `${currentData.visibility} km`,
              icon: Eye,
              color: "from-blue-500 to-cyan-500",
            },
            {
              label: "UV Index",
              value: currentData.uvIndex,
              icon: Sun,
              color: "from-yellow-500 to-orange-500",
            },
            {
              label: "Wind",
              value: `${currentData.windSpeed} km/h ${currentData.windDirection}`,
              icon: Wind,
              color: "from-teal-500 to-green-500",
            },
          ].map((stat, idx) => (
            <div
              key={idx}
              className="bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 hover:bg-white/15 transition-all"
            >
              <div className="flex items-center justify-between mb-2">
                <stat.icon className="w-5 h-5 text-white" />
                <div
                  className={`w-2 h-2 rounded-full bg-gradient-to-r ${stat.color}`}
                ></div>
              </div>
              <div className="text-2xl font-bold text-white mb-1">
                {stat.value}
              </div>
              <div className="text-xs text-gray-400">{stat.label}</div>
            </div>
          ))}
        </div>

        <div className="mb-6 flex space-x-2 bg-white/10 backdrop-blur-md rounded-xl p-1">
          {[
            { id: "overview", label: "Overview", icon: Activity },
            { id: "trends", label: "Trends", icon: TrendingUp },
            { id: "pollutants", label: "Pollutants", icon: Zap },
            { id: "health", label: "Health Impact", icon: Heart },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 py-3 px-4 rounded-lg font-medium transition-all flex items-center justify-center space-x-2 ${
                activeTab === tab.id
                  ? "bg-gradient-to-r from-purple-500 to-blue-500 text-white shadow-lg"
                  : "text-white hover:bg-white/10"
              }`}
            >
              <tab.icon className="w-4 h-4" />
              <span className="hidden sm:inline">{tab.label}</span>
            </button>
          ))}
        </div>

        {activeTab === "overview" && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              <div className="lg:col-span-1 bg-gradient-to-br from-white/15 to-white/5 backdrop-blur-md rounded-2xl p-6 border border-white/20 shadow-2xl">
                <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                  <Activity className="w-5 h-5 mr-2" />
                  Current AQI
                </h3>
                <div className="text-center py-8">
                  <div className="relative inline-block">
                    <div
                      className="text-8xl font-black mb-2 animate-pulse"
                      style={{ color: currentData.color }}
                    >
                      {currentData.aqi}
                    </div>
                    <div
                      className="absolute -top-2 -right-2 w-6 h-6 rounded-full animate-ping"
                      style={{
                        backgroundColor: currentData.color,
                        opacity: 0.4,
                      }}
                    ></div>
                  </div>
                  <div
                    className="text-2xl font-bold mb-2"
                    style={{ color: currentData.color }}
                  >
                    {category.label}
                  </div>
                  <p className="text-gray-300 text-sm px-4">{category.desc}</p>
                  <div className="mt-6 pt-6 border-t border-white/20">
                    <div className="flex items-center justify-center text-gray-300 mb-2">
                      <Clock className="w-4 h-4 mr-2" />
                      <span className="text-sm">Last Updated</span>
                    </div>
                    <span className="text-white font-semibold">
                      {currentData.timestamp}
                    </span>
                  </div>
                </div>
              </div>

              <div className="lg:col-span-2 grid grid-cols-2 gap-4">
                {[
                  {
                    label: "PM2.5",
                    value: currentData.pm25,
                    unit: "µg/m³",
                    icon: "🔴",
                    gradient: "from-red-500 to-pink-500",
                  },
                  {
                    label: "PM10",
                    value: currentData.pm10,
                    unit: "µg/m³",
                    icon: "🟠",
                    gradient: "from-orange-500 to-yellow-500",
                  },
                  {
                    label: "NO₂",
                    value: currentData.no2,
                    unit: "µg/m³",
                    icon: "🟡",
                    gradient: "from-yellow-500 to-amber-500",
                  },
                  {
                    label: "SO₂",
                    value: currentData.so2,
                    unit: "µg/m³",
                    icon: "🟢",
                    gradient: "from-green-500 to-emerald-500",
                  },
                  {
                    label: "CO",
                    value: currentData.co,
                    unit: "mg/m³",
                    icon: "🔵",
                    gradient: "from-blue-500 to-indigo-500",
                  },
                  {
                    label: "O₃",
                    value: currentData.o3,
                    unit: "µg/m³",
                    icon: "🟣",
                    gradient: "from-purple-500 to-violet-500",
                  },
                ].map((metric) => (
                  <div
                    key={metric.label}
                    className="relative bg-white/10 backdrop-blur-md rounded-xl p-4 border border-white/20 hover:scale-105 transition-transform overflow-hidden group"
                  >
                    <div
                      className={`absolute inset-0 bg-gradient-to-br ${metric.gradient} opacity-0 group-hover:opacity-10 transition-opacity`}
                    ></div>
                    <div className="relative">
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-gray-300 text-sm font-medium">
                          {metric.label}
                        </span>
                        <span className="text-3xl">{metric.icon}</span>
                      </div>
                      <div className="text-white text-4xl font-bold mb-1">
                        {metric.value}
                      </div>
                      <div className="text-gray-400 text-xs">{metric.unit}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
                <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                  <Cloud className="w-5 h-5 mr-2" />
                  Weather Conditions
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  {[
                    {
                      label: "Temperature",
                      value: `${currentData.temperature}°C`,
                      icon: Thermometer,
                      color: "text-orange-400",
                    },
                    {
                      label: "Humidity",
                      value: `${currentData.humidity}%`,
                      icon: Droplets,
                      color: "text-blue-400",
                    },
                    {
                      label: "Wind Speed",
                      value: `${currentData.windSpeed} km/h`,
                      icon: Wind,
                      color: "text-teal-400",
                    },
                    {
                      label: "Pressure",
                      value: `${currentData.pressure} hPa`,
                      icon: Activity,
                      color: "text-purple-400",
                    },
                  ].map((item) => (
                    <div
                      key={item.label}
                      className="bg-white/5 rounded-xl p-4 border border-white/10"
                    >
                      <item.icon className={`w-6 h-6 ${item.color} mb-2`} />
                      <div className="text-white text-2xl font-bold">
                        {item.value}
                      </div>
                      <div className="text-gray-400 text-sm mt-1">
                        {item.label}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
                <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                  <Building2 className="w-5 h-5 mr-2" />
                  Pollution Sources
                </h3>
                <ResponsiveContainer width="100%" height={200}>
                  <PieChart>
                    <Pie
                      data={sourceData}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, percent }) =>
                        `${name} ${(percent * 100).toFixed(0)}%`
                      }
                      outerRadius={80}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {sourceData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>
        )}

        {activeTab === "trends" && (
          <div className="space-y-6">
            <div className="flex justify-end space-x-2">
              {["24h", "7d", "30d"].map((range) => (
                <button
                  key={range}
                  onClick={() => setTimeRange(range)}
                  className={`px-4 py-2 rounded-lg font-medium transition-all ${
                    timeRange === range
                      ? "bg-purple-500 text-white"
                      : "bg-white/10 text-gray-300 hover:bg-white/20"
                  }`}
                >
                  {range === "24h"
                    ? "24 Hours"
                    : range === "7d"
                    ? "7 Days"
                    : "30 Days"}
                </button>
              ))}
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                <TrendingUp className="w-5 h-5 mr-2" />
                24-Hour AQI Trend
              </h3>
              <ResponsiveContainer width="100%" height={350}>
                <AreaChart data={historicalData}>
                  <defs>
                    <linearGradient
                      id="aqiGradient"
                      x1="0"
                      y1="0"
                      x2="0"
                      y2="1"
                    >
                      <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.8} />
                      <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff20" />
                  <XAxis dataKey="hour" stroke="#fff" />
                  <YAxis stroke="#fff" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(0,0,0,0.9)",
                      border: "1px solid rgba(139, 92, 246, 0.5)",
                      borderRadius: "12px",
                      color: "#fff",
                      padding: "12px",
                    }}
                  />
                  <Area
                    type="monotone"
                    dataKey="aqi"
                    stroke="#8b5cf6"
                    strokeWidth={3}
                    fillOpacity={1}
                    fill="url(#aqiGradient)"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4">
                Pollutant Levels Throughout the Day
              </h3>
              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={historicalData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff20" />
                  <XAxis dataKey="hour" stroke="#fff" />
                  <YAxis stroke="#fff" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(0,0,0,0.9)",
                      border: "1px solid rgba(139, 92, 246, 0.5)",
                      borderRadius: "12px",
                      color: "#fff",
                      padding: "12px",
                    }}
                  />
                  <Legend />
                  <Line
                    type="monotone"
                    dataKey="pm25"
                    stroke="#ef4444"
                    strokeWidth={2}
                    name="PM2.5"
                    dot={{ r: 3 }}
                  />
                  <Line
                    type="monotone"
                    dataKey="pm10"
                    stroke="#f97316"
                    strokeWidth={2}
                    name="PM10"
                    dot={{ r: 3 }}
                  />
                  <Line
                    type="monotone"
                    dataKey="no2"
                    stroke="#fbbf24"
                    strokeWidth={2}
                    name="NO₂"
                    dot={{ r: 3 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                <Calendar className="w-5 h-5 mr-2" />
                Weekly AQI Overview
              </h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={weeklyData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff20" />
                  <XAxis dataKey="day" stroke="#fff" />
                  <YAxis stroke="#fff" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(0,0,0,0.9)",
                      border: "1px solid rgba(139, 92, 246, 0.5)",
                      borderRadius: "12px",
                      color: "#fff",
                    }}
                  />
                  <Legend />
                  <Bar dataKey="maxAQI" fill="#ef4444" name="Max AQI" />
                  <Bar dataKey="avgAQI" fill="#8b5cf6" name="Avg AQI" />
                  <Bar dataKey="minAQI" fill="#10b981" name="Min AQI" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}

        {activeTab === "pollutants" && (
          <div className="space-y-6">
            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4">
                Pollutant Levels Comparison
              </h3>
              <ResponsiveContainer width="100%" height={400}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="#ffffff40" />
                  <PolarAngleAxis dataKey="pollutant" stroke="#fff" />
                  <PolarRadiusAxis stroke="#fff" />
                  <Radar
                    name="Current Level"
                    dataKey="current"
                    stroke="#8b5cf6"
                    fill="#8b5cf6"
                    fillOpacity={0.6}
                  />
                  <Radar
                    name="Safe Limit"
                    dataKey="safe"
                    stroke="#10b981"
                    fill="#10b981"
                    fillOpacity={0.3}
                  />
                  <Legend />
                  <Tooltip />
                </RadarChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4">
                Current Levels vs Safety Limits
              </h3>
              <ResponsiveContainer width="100%" height={400}>
                <BarChart data={pollutantData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff20" />
                  <XAxis dataKey="name" stroke="#fff" />
                  <YAxis stroke="#fff" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: "rgba(0,0,0,0.9)",
                      border: "1px solid rgba(139, 92, 246, 0.5)",
                      borderRadius: "12px",
                      color: "#fff",
                    }}
                  />
                  <Legend />
                  <Bar dataKey="value" fill="#8b5cf6" name="Current" />
                  <Bar dataKey="limit" fill="#10b981" name="Safe Limit" />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {pollutantData.map((pollutant, idx) => (
                <div
                  key={idx}
                  className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20 hover:bg-white/15 transition-all"
                >
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="text-white text-xl font-bold">
                      {pollutant.name}
                    </h4>
                    <span className="text-2xl">
                      {getTrendIcon(pollutant.trend)}
                    </span>
                  </div>

                  <div className="mb-4">
                    <div className="flex items-baseline space-x-2 mb-2">
                      <span className="text-4xl font-bold text-white">
                        {pollutant.value}
                      </span>
                      <span className="text-gray-400 text-sm">
                        {pollutant.unit}
                      </span>
                    </div>
                    <div className="text-sm text-gray-300">
                      Safe Limit:{" "}
                      <span className="text-green-400 font-semibold">
                        {pollutant.limit} {pollutant.unit}
                      </span>
                    </div>
                  </div>

                  <div className="mb-4">
                    <div className="flex items-center justify-between text-sm mb-2">
                      <span className="text-gray-400">Level</span>
                      <span
                        className={`font-semibold ${
                          pollutant.impact === "High"
                            ? "text-red-400"
                            : pollutant.impact === "Moderate"
                            ? "text-yellow-400"
                            : "text-green-400"
                        }`}
                      >
                        {pollutant.impact}
                      </span>
                    </div>
                    <div className="w-full bg-gray-700 rounded-full h-2">
                      <div
                        className={`h-2 rounded-full transition-all ${
                          pollutant.impact === "High"
                            ? "bg-red-500"
                            : pollutant.impact === "Moderate"
                            ? "bg-yellow-500"
                            : "bg-green-500"
                        }`}
                        style={{
                          width: `${Math.min(
                            (pollutant.value / pollutant.limit) * 100,
                            100
                          )}%`,
                        }}
                      ></div>
                    </div>
                  </div>

                  <div className="bg-white/5 rounded-lg p-3 border border-white/10">
                    <div className="text-xs text-gray-400 mb-1">
                      Health Effect:
                    </div>
                    <div className="text-sm text-gray-300">
                      {pollutant.healthEffect}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === "health" && (
          <div className="space-y-6">
            <div className="bg-gradient-to-br from-white/15 to-white/5 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-xl font-bold mb-4 flex items-center">
                <Heart className="w-6 h-6 mr-2 text-red-400" />
                Health Risk Assessment
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {[
                  {
                    group: "General Public",
                    icon: Users,
                    risk: "Moderate",
                    color: "yellow",
                    advice:
                      "Reduce prolonged outdoor activities. Use masks if necessary.",
                  },
                  {
                    group: "Sensitive Groups",
                    icon: Heart,
                    risk: "High",
                    color: "red",
                    advice:
                      "Avoid outdoor activities. Stay indoors with air purifiers.",
                  },
                  {
                    group: "Children & Elderly",
                    icon: AlertCircle,
                    risk: "High",
                    color: "red",
                    advice:
                      "Limit all outdoor exposure. Monitor health closely.",
                  },
                ].map((item, idx) => (
                  <div
                    key={idx}
                    className="bg-white/10 rounded-xl p-5 border border-white/20"
                  >
                    <div className="flex items-center mb-3">
                      <item.icon
                        className={`w-6 h-6 mr-2 ${
                          item.color === "red"
                            ? "text-red-400"
                            : "text-yellow-400"
                        }`}
                      />
                      <h4 className="text-white font-semibold">{item.group}</h4>
                    </div>
                    <div
                      className={`inline-block px-3 py-1 rounded-full text-sm font-semibold mb-3 ${
                        item.color === "red"
                          ? "bg-red-500/20 text-red-300"
                          : "bg-yellow-500/20 text-yellow-300"
                      }`}
                    >
                      {item.risk} Risk
                    </div>
                    <p className="text-gray-300 text-sm">{item.advice}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
                <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                  <AlertCircle className="w-5 h-5 mr-2 text-red-400" />
                  Possible Symptoms
                </h3>
                <div className="space-y-3">
                  {[
                    "Coughing and throat irritation",
                    "Shortness of breath",
                    "Eye irritation and watering",
                    "Chest tightness",
                    "Fatigue and dizziness",
                    "Aggravated asthma symptoms",
                  ].map((symptom, idx) => (
                    <div
                      key={idx}
                      className="flex items-start space-x-3 bg-white/5 rounded-lg p-3 border border-white/10"
                    >
                      <div className="w-2 h-2 rounded-full bg-red-400 mt-2 flex-shrink-0"></div>
                      <span className="text-gray-300 text-sm">{symptom}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
                <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                  <Info className="w-5 h-5 mr-2 text-blue-400" />
                  Protective Measures
                </h3>
                <div className="space-y-3">
                  {[
                    "Wear N95/N99 masks outdoors",
                    "Use air purifiers indoors",
                    "Keep windows and doors closed",
                    "Stay hydrated",
                    "Avoid outdoor exercise",
                    "Monitor air quality regularly",
                  ].map((measure, idx) => (
                    <div
                      key={idx}
                      className="flex items-start space-x-3 bg-white/5 rounded-lg p-3 border border-white/10"
                    >
                      <div className="w-2 h-2 rounded-full bg-green-400 mt-2 flex-shrink-0"></div>
                      <span className="text-gray-300 text-sm">{measure}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20">
              <h3 className="text-white text-lg font-semibold mb-4 flex items-center">
                <Activity className="w-5 h-5 mr-2 text-purple-400" />
                Long-term Health Effects
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {[
                  {
                    title: "Respiratory",
                    effects: [
                      "Chronic bronchitis",
                      "Reduced lung function",
                      "Asthma development",
                    ],
                  },
                  {
                    title: "Cardiovascular",
                    effects: [
                      "Heart disease",
                      "High blood pressure",
                      "Stroke risk",
                    ],
                  },
                  {
                    title: "Neurological",
                    effects: [
                      "Cognitive decline",
                      "Dementia risk",
                      "Depression",
                    ],
                  },
                  {
                    title: "Other",
                    effects: ["Cancer risk", "Diabetes", "Premature death"],
                  },
                ].map((category, idx) => (
                  <div
                    key={idx}
                    className="bg-white/5 rounded-xl p-4 border border-white/10"
                  >
                    <h4 className="text-white font-semibold mb-3">
                      {category.title}
                    </h4>
                    <ul className="space-y-2">
                      {category.effects.map((effect, i) => (
                        <li
                          key={i}
                          className="text-gray-300 text-sm flex items-start"
                        >
                          <span className="text-red-400 mr-2">•</span>
                          {effect}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </main>

      <footer className="bg-white/5 backdrop-blur-md border-t border-white/20 mt-12">
        <div className="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="text-gray-400 text-sm mb-4 md:mb-0">
              © 2025 AirAware. Data updated every minute. Sources: EPA, WHO,
              Local Monitoring Stations
            </div>
            <div className="flex items-center space-x-6">
              <a
                href="https://www.epa.gov/air-quality"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                About
              </a>
              <a
                href="https://docs.anthropic.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                API
              </a>
              <a
                href="mailto:contact@airaware.example.com"
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                Contact
              </a>
              <a
                href="https://www.who.int/health-topics/air-pollution"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                Privacy
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default AirAwareDashboard;